/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.frnchnrd.authenticateme;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_action_next_item=0x7f020000;
        public static final int ic_action_previous_item=0x7f020001;
        public static final int ic_action_remove=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int screen=0x7f020004;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
